version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: quotes
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: quotes
      API_PORT: 8080
    ports:
      - "8080:8080"

volumes:
  pgdata:
